# Generated by Django 4.2.14 on 2024-10-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('color', models.CharField(max_length=30)),
                ('num_doors', models.IntegerField()),
                ('seating_capacity', models.IntegerField()),
            ],
        ),
    ]
